// src/sections/Property/propertyData.ts

import img1 from "../../assets/images/properties/1.jpg";
import img2 from "../../assets/images/properties/2.jpg";
import img3 from "../../assets/images/properties/3.jpg";
import img4 from "../../assets/images/properties/4.jpg";
import img5 from "../../assets/images/properties/5.jpg";
import img6 from "../../assets/images/properties/6.jpg";
import img7 from "../../assets/images/properties/7.jpg";
import img8 from "../../assets/images/properties/8.jpg";
import img9 from "../../assets/images/properties/9.jpg";
import img10 from "../../assets/images/properties/10.jpg";
import img11 from "../../assets/images/properties/11.jpg";
import img12 from "../../assets/images/properties/12.jpg";
import img13 from "../../assets/images/properties/13.jpg";
import img14 from "../../assets/images/properties/14.jpg";
import img15 from "../../assets/images/properties/15.jpg";
import img16 from "../../assets/images/properties/16.jpg";
import img17 from "../../assets/images/properties/17.jpg";
import img18 from "../../assets/images/properties/18.jpg";
import img19 from "../../assets/images/properties/19.jpg";
import img20 from "../../assets/images/properties/20.jpg";
import img21 from "../../assets/images/properties/21.jpg";

export const propertyData = {
  badge: "LATEST PROPERTIES",
  title: "Fresh on the market",
  description:
    "Stay ahead of the curve with our newest listings — handpicked homes and investments recently added to the market.",

  sidebar: {
    intro:
      "Browse our latest properties — from cozy family homes to luxury estates. Each listing is carefully selected to match different lifestyles and budgets.",
    types: ["All", "Sell", "Rent"],
    categories: ["Apartments", "Condos", "Houses", "Villas"],
    locations: ["Brooklyn", "Manhattan", "Queens", "Staten Island", "The Bronx"],
  },

  listings: [
    {
      name: "South Sunlight Apartment",
      location: "Staten Island",
      type: "Apartment",
      status: "Rent",
      beds: 4,
      baths: 2,
      sqft: 160,
      agent: "Rachel Gray",
      price: "$1,200",
      image: img1,
    },
    {
      name: "Marble House",
      location: "Queens",
      type: "House",
      status: "Sell",
      beds: 4,
      baths: 3,
      sqft: 250,
      agent: "Steve Panter",
      price: "$550,000",
      image: img2,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img4,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img5,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img6,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img7,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img8,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img9,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img10,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img11,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img12,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img13,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img14,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img15,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img16,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img17,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img18,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img19,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img20,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img21,
    }
  ],
};
