// src/sections/Property/propertyData.ts

import img1 from "../../assets/images/1.png";
import img2 from "../../assets/images/2.jpg";
import img3 from "../../assets/images/3.jpeg";
// ... continue importing up to img21

export const propertyData = {
  badge: "LATEST PROPERTIES",
  title: "Fresh on the market",
  description:
    "Stay ahead of the curve with our newest listings — handpicked homes and investments recently added to the market.",

  sidebar: {
    intro:
      "Browse our latest properties — from cozy family homes to luxury estates. Each listing is carefully selected to match different lifestyles and budgets.",
    types: ["All", "Sell", "Rent"],
    categories: ["Apartments", "Condos", "Houses", "Villas"],
    locations: ["Brooklyn", "Manhattan", "Queens", "Staten Island", "The Bronx"],
  },

  listings: [
    {
      name: "South Sunlight Apartment",
      location: "Staten Island",
      type: "Apartment",
      status: "Rent",
      beds: 4,
      baths: 2,
      sqft: 160,
      agent: "Rachel Gray",
      price: "$1,200",
      image: img1,
    },
    {
      name: "Marble House",
      location: "Queens",
      type: "House",
      status: "Sell",
      beds: 4,
      baths: 3,
      sqft: 250,
      agent: "Steve Panter",
      price: "$550,000",
      image: img2,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    },
    {
      name: "Family Mansion",
      location: "Manhattan",
      type: "Apartment",
      status: "Rent",
      beds: 2,
      baths: 2,
      sqft: 150,
      agent: "Rachel Gray",
      price: "$2,200",
      image: img3,
    }
    // ... continue until you have 21 listings
  ],
};
